language: ruby
rvm:
- ree
- 1.9.3
- 2.0.0
script: bundle exec rake rubocop test
notifications:
  email:
    recipients: daniel.buch+resque-scheduler@gmail.com
deploy:
  provider: rubygems
  api_key:
    secure: dM97lL/jTu14mEHD2Ih/vQfZ8cWJWb+DQ8UKZjkD2JfYtvwEAlkPG9RrrDkSHb5qkYxG2VAhjyx/0MZJ0TsVL6wrLMC9gcJb3yomw2Sch2Noj68tEndiSUHnxrB9gKzbhHbjLQXDqYf4Hco9/PHHQp4piFPJhLzNZRehIuTJPcA=
  gem: resque-scheduler
  on:
    tags: true
    repo: resque/resque-scheduler
    rvm: 2.0.0
